services:
  # Main application
  app:
    build: .
    container_name: yt-downloader-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PUBLIC_URL=${REDIS_PUBLIC_URL}
      - NODE_ENV=development
      - REDIS_VIEWER_PASSWORD=${REDIS_VIEWER_PASSWORD:-admin123}
    volumes:
      - ./downloads:/app/downloads
      - ./public:/app/public
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RedisInsight for database management
  redisinsight:
    image: redis/redisinsight:latest
    container_name: yt-downloader-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    restart: unless-stopped

volumes:
  redisinsight_data:
    driver: local