services:
  # Redis service for caching and history
  redis:
    image: redis:7-alpine
    container_name: yt-downloader-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Main application
  app:
    build: .
    container_name: yt-downloader-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - REDIS_VIEWER_PASSWORD=${REDIS_VIEWER_PASSWORD:-admin123}
    volumes:
      - ./downloads:/app/downloads
      - ./public:/app/public
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RedisInsight for database management
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: yt-downloader-redisinsight
    ports:
      - "8001:8001"
    environment:
      - RIPORT=8001
      - RIHOST=0.0.0.0
    volumes:
      - redisinsight_data:/db
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  redisinsight_data:
    driver: local